export const copy = {
    vi: {
        heroEyebrow: "Logistics và khai báo hải quan tại Lao Bảo",
        heroLead: "Vận tải xuyên biên giới",
        heroHighlight: "và khai báo hải quan",
        heroTail: "thuận lợi hơn.",
        heroBody: "Một đầu mối xử lý chứng từ, thủ tục và vận chuyển trên tuyến Việt Nam – Lào – Thái Lan. Quy trình rõ ràng, phản hồi nhanh và luôn có người theo sát lô hàng.",
        heroImageAlt: "Xe hàng làm thủ tục tại Cửa khẩu Quốc tế Lao Bảo",
        corridorDesk: "Trung tâm điều phối EWEC",
        corridorStatus: "Đang kết nối",
        corridorPoints: ["Quảng Trị", "Savannakhet", "Mukdahan"],
        heroMetrics: [
            { value: "01", label: "Đầu mối chịu trách nhiệm" },
            { value: "06", label: "Nhóm chứng từ rà soát" },
            { value: "04", label: "Chặng kiểm soát lô hàng" },
            { value: "24/7", label: "Hỗ trợ vận hành" },
        ],
        trackingEyebrow: "Cổng theo dõi mới",
        trackingTitle: "Khách hàng tự xem tiến độ, hệ thống tự báo khi thông quan.",
        trackingBody: "Timeline, trạng thái hải quan và checklist chứng từ được gom vào một mã tra cứu duy nhất.",
        trackingCta: "Mở cổng theo dõi",
        trackingDemo: "Xem mã demo",
        trackingPillars: ["Cập nhật mỗi 5 giây", "Báo Zalo & email", "Không lộ thông tin liên hệ"],
        trackingMock: {
            control: "Bảng điều phối khách hàng",
            live: "Dữ liệu trực tiếp",
            status: "Đã thông quan",
            code: "VILA-EWEC-002",
            cargo: "Linh kiện điện tử · 18,4 tấn",
            route: "Đà Nẵng → Lao Bảo → Savannakhet",
            progress: "06 / 08 chặng",
            metrics: [
                { label: "Khối lượng", value: "18,4 tấn" },
                { label: "ETA Savannakhet", value: "16:45 hôm nay" },
                { label: "Chứng từ", value: "06 / 06 đã đủ" },
                { label: "Điều phối viên", value: "Nguyễn Minh Anh" },
            ],
            notificationTitle: "Thông quan lúc 10:42",
            notificationBody: "Zalo và email đã gửi tới khách hàng.",
            timeline: ["Tiếp nhận", "Mở tờ khai", "Kiểm hóa", "Thông quan", "Vận chuyển"],
        },
        primaryCta: "Nhận tư vấn miễn phí",
        secondaryCta: "Xem dịch vụ",
        trust: ["Đại lý hải quan được công nhận", "Hỗ trợ 24/7", "Tuyến Việt Nam – Lào – Thái Lan"],
        quickServices: [
            { title: "Khai báo hải quan", description: "Kiểm tra hồ sơ, mã HS và mở tờ khai chính xác." },
            { title: "Vận tải xuyên biên giới", description: "Điều phối tuyến Việt Nam – Lào – Thái Lan xuyên suốt." },
            { title: "Kho bãi & gom hàng", description: "Lưu kho, gom chuyến và giao nhận linh hoạt." },
            { title: "Giao nhận tại cửa khẩu", description: "Theo sát phương tiện, chứng từ và tiến độ thông quan." },
        ],
        documentsEyebrow: "Bộ hồ sơ thường gặp",
        documentsTitle: "Chuẩn bị đúng chứng từ ngay từ đầu",
        documentsBody: "Danh mục thực tế có thể thay đổi theo mặt hàng và loại hình xuất nhập khẩu. Chúng tôi sẽ rà soát trước khi mở tờ khai.",
        documents: [
            { title: "Hóa đơn thương mại", meta: "Commercial Invoice" },
            { title: "Phiếu đóng gói", meta: "Packing List" },
            { title: "Hợp đồng ngoại thương", meta: "Sales Contract" },
            { title: "Chứng từ vận tải", meta: "Bill of Lading / CMR" },
            { title: "Chứng nhận xuất xứ", meta: "C/O nếu áp dụng" },
            { title: "Giấy phép chuyên ngành", meta: "Theo chính sách mặt hàng" },
        ],
        routesEyebrow: "Phạm vi kết nối",
        routesTitle: "Một đầu mối trên hành lang Việt Nam – Lào – Thái Lan",
        routesBody: "Lộ trình được tư vấn theo loại hàng, điểm nhận giao và yêu cầu thời gian của từng lô.",
        routes: [
            { title: "Lao Bảo ↔ Dansavanh", description: "Phối hợp chứng từ và giao nhận tại cặp cửa khẩu." },
            { title: "Quảng Trị ↔ Savannakhet", description: "Điều phối vận chuyển và tiến độ bàn giao." },
            { title: "Việt Nam ↔ Lào ↔ Thái Lan", description: "Tư vấn phương án xuyên biên giới theo từng lô hàng." },
        ],
        servicesEyebrow: "Dịch vụ trọng tâm",
        servicesTitle: "Giải pháp trọn gói cho từng lô hàng",
        servicesBody: "Từ kiểm tra hồ sơ đến giao hàng, mỗi bước đều có người phụ trách và thời gian xử lý cụ thể.",
        allServices: "Xem tất cả dịch vụ",
        fallbackServices: [
            {
                category: "Khai báo hải quan",
                title: "Tư vấn hồ sơ và mã HS",
                description: "Kiểm tra chính sách mặt hàng, thuế và chứng từ trước khi mở tờ khai.",
            },
            {
                category: "Vận tải quốc tế",
                title: "Vận chuyển Việt Nam – Lào – Thái Lan",
                description: "Điều phối phương tiện và lịch trình xuyên suốt tuyến hành lang kinh tế Đông – Tây.",
            },
            {
                category: "Kho vận",
                title: "Kho bãi, gom hàng và giao nhận",
                description: "Phương án lưu kho và gom chuyến linh hoạt, giúp giảm thời gian chờ và chi phí.",
            },
            {
                category: "Tại cửa khẩu",
                title: "Giao nhận Lao Bảo – Dansavanh",
                description: "Phối hợp phương tiện, chứng từ và bàn giao hàng tại cặp cửa khẩu trọng điểm.",
            },
            {
                category: "Tuân thủ",
                title: "Kiểm tra chính sách mặt hàng",
                description: "Rà soát giấy phép, xuất xứ, thuế và yêu cầu quản lý chuyên ngành trước khi hàng đi.",
            },
            {
                category: "Điều phối",
                title: "Theo dõi chứng từ và phương tiện",
                description: "Một đầu mối cập nhật hồ sơ, vị trí phương tiện và tiến độ bàn giao xuyên suốt.",
            },
        ],
        processEyebrow: "Quy trình minh bạch",
        processTitle: "Bạn luôn biết hồ sơ đang ở bước nào",
        processBody: "Đội ngũ VILA SANMYSHI phối hợp chứng từ và phương tiện trong cùng một luồng công việc.",
        processSteps: [
            { title: "Tiếp nhận thông tin", description: "Kiểm tra invoice, packing list, hợp đồng và yêu cầu giao nhận." },
            { title: "Rà soát hồ sơ", description: "Đối chiếu mã HS, giấy phép, thuế và chính sách chuyên ngành." },
            { title: "Khai báo và điều phối", description: "Mở tờ khai, bố trí xe và cập nhật tiến độ tại cửa khẩu." },
            { title: "Bàn giao và đối soát", description: "Hoàn tất giao hàng, chứng từ và chi phí minh bạch." },
        ],
        proofEyebrow: "Lý do khách hàng lựa chọn",
        proofTitle: "Kinh nghiệm thực tế, quy trình rõ ràng",
        proofBody: "Sự an tâm đến từ một đội ngũ hiểu tuyến đường, nắm thủ tục và phản hồi đúng lúc.",
        stats: [
            { value: "2018", label: "Năm thành lập" },
            { value: "24/7", label: "Hỗ trợ vận hành" },
            { value: "03", label: "Thị trường kết nối" },
            { value: "01", label: "Đầu mối xuyên suốt" },
        ],
        newsEyebrow: "Kiến thức chuyên ngành",
        newsTitle: "Cập nhật chính sách và thị trường",
        readMore: "Đọc bài viết",
        faqEyebrow: "Thông tin cần biết",
        faqTitle: "Câu hỏi trước khi gửi hồ sơ",
        faqs: [
            {
                question: "Cần gửi những gì để được kiểm tra hồ sơ?",
                answer: "Bạn có thể gửi invoice, packing list, hợp đồng, mô tả hàng hóa và tuyến dự kiến. Đội ngũ sẽ phản hồi nếu cần bổ sung chứng từ.",
            },
            {
                question: "VILA SANMYSHI có hỗ trợ tra mã HS không?",
                answer: "Có. Chúng tôi tiếp nhận thông tin hàng hóa, đối chiếu chính sách và tư vấn mã HS phù hợp trước khi khai báo.",
            },
            {
                question: "Có thể kết hợp khai báo và vận chuyển xuyên biên giới?",
                answer: "Có. Phương án được xây dựng theo loại hàng, điểm nhận giao, phương tiện và yêu cầu thời gian của từng lô.",
            },
            {
                question: "Tiến độ lô hàng được cập nhật như thế nào?",
                answer: "Mỗi lô hàng có một đầu mối theo sát hồ sơ, phương tiện, tình trạng tại cửa khẩu và thời điểm bàn giao.",
            },
        ],
        ctaTitle: "Cần kiểm tra hồ sơ trước khi mở tờ khai?",
        ctaBody: "Gửi thông tin lô hàng, đội ngũ của chúng tôi sẽ phản hồi phương án phù hợp và dễ hiểu.",
        ctaButton: "Liên hệ tư vấn",
    },
    en: {
        heroEyebrow: "Logistics and customs support at Lao Bao",
        heroLead: "Cross-border transport",
        heroHighlight: "and customs clearance",
        heroTail: "made simpler.",
        heroBody: "One team handles documents, customs procedures and transport across Vietnam, Laos and Thailand with clear updates at every step.",
        heroImageAlt: "Cargo trucks clearing Lao Bao International Border Gate",
        corridorDesk: "EWEC operations desk",
        corridorStatus: "Live corridor",
        corridorPoints: ["Quang Tri", "Savannakhet", "Mukdahan"],
        heroMetrics: [
            { value: "01", label: "Accountable contact" },
            { value: "06", label: "Document groups reviewed" },
            { value: "04", label: "Controlled shipment stages" },
            { value: "24/7", label: "Operations support" },
        ],
        trackingEyebrow: "New tracking portal",
        trackingTitle: "Clients see progress while the system reports customs clearance.",
        trackingBody: "Timeline, customs status and document readiness are connected through one tracking code.",
        trackingCta: "Open tracking portal",
        trackingDemo: "View demo code",
        trackingPillars: ["Refreshes every 5 seconds", "Zalo & email alerts", "Contact details stay private"],
        trackingMock: {
            control: "Customer operations board",
            live: "Live data",
            status: "Customs cleared",
            code: "VILA-EWEC-002",
            cargo: "Electronic components · 18.4 tonnes",
            route: "Da Nang → Lao Bao → Savannakhet",
            progress: "06 / 08 stages",
            metrics: [
                { label: "Gross weight", value: "18.4 tonnes" },
                { label: "ETA Savannakhet", value: "16:45 today" },
                { label: "Documents", value: "06 / 06 complete" },
                { label: "Coordinator", value: "Nguyen Minh Anh" },
            ],
            notificationTitle: "Cleared at 10:42",
            notificationBody: "Zalo and email notices were sent to the client.",
            timeline: ["Received", "Declared", "Inspection", "Cleared", "In transit"],
        },
        primaryCta: "Get free advice",
        secondaryCta: "View services",
        trust: ["Licensed customs agent", "24/7 support", "Vietnam – Laos – Thailand route"],
        quickServices: [
            { title: "Customs clearance", description: "Accurate document, HS code and declaration support." },
            { title: "Cross-border transport", description: "Coordinated Vietnam – Laos – Thailand routes." },
            { title: "Warehousing & consolidation", description: "Flexible storage, consolidation and delivery." },
            { title: "Border-gate handling", description: "Close tracking of vehicles, documents and clearance." },
        ],
        documentsEyebrow: "Common document set",
        documentsTitle: "Prepare the right documents from the start",
        documentsBody: "Requirements vary by commodity and customs regime. Our team reviews the file before the declaration is submitted.",
        documents: [
            { title: "Commercial invoice", meta: "Transaction value and terms" },
            { title: "Packing list", meta: "Packing, weight and quantity" },
            { title: "Sales contract", meta: "Commercial agreement" },
            { title: "Transport document", meta: "Bill of Lading / CMR" },
            { title: "Certificate of origin", meta: "When applicable" },
            { title: "Specialist permits", meta: "Based on commodity policy" },
        ],
        routesEyebrow: "Connected corridors",
        routesTitle: "One contact across Vietnam, Laos and Thailand",
        routesBody: "Each route is planned around the cargo type, pickup and delivery points, and required timeline.",
        routes: [
            { title: "Lao Bao ↔ Dansavanh", description: "Document and border-gate delivery coordination." },
            { title: "Quang Tri ↔ Savannakhet", description: "Transport planning and delivery progress." },
            { title: "Vietnam ↔ Laos ↔ Thailand", description: "Cross-border options tailored to each shipment." },
        ],
        servicesEyebrow: "Core services",
        servicesTitle: "Complete support for every shipment",
        servicesBody: "From document review to final delivery, every step has a clear owner and timeline.",
        allServices: "Explore all services",
        fallbackServices: [
            { category: "Customs", title: "Document and HS code advice", description: "Review commodity policy, tax and documents before filing." },
            { category: "Transport", title: "Vietnam – Laos – Thailand transport", description: "Coordinate vehicles and schedules across the East–West Economic Corridor." },
            { category: "Warehousing", title: "Storage, consolidation and delivery", description: "Flexible storage and consolidation plans that reduce waiting time and cost." },
            { category: "Border handling", title: "Lao Bao – Dansavanh handover", description: "Coordinate vehicles, documents and cargo handover at the key border pair." },
            { category: "Compliance", title: "Commodity policy review", description: "Check permits, origin, tax and specialist requirements before cargo moves." },
            { category: "Coordination", title: "Document and vehicle tracking", description: "One contact reports document, vehicle and final handover progress throughout." },
        ],
        processEyebrow: "A transparent process",
        processTitle: "You always know what happens next",
        processBody: "VILA SANMYSHI coordinates documents and vehicles in one consistent workflow.",
        processSteps: [
            { title: "Receive information", description: "Review invoices, packing lists, contracts and delivery needs." },
            { title: "Check documents", description: "Verify HS codes, permits, taxes and specialist policies." },
            { title: "File and coordinate", description: "Submit declarations, arrange trucks and report border progress." },
            { title: "Deliver and reconcile", description: "Complete delivery, documents and cost reconciliation." },
        ],
        proofEyebrow: "Why clients choose us",
        proofTitle: "Practical experience and a clear process",
        proofBody: "Confidence comes from a team that knows the route, understands the procedure and responds on time.",
        stats: [
            { value: "2018", label: "Established" },
            { value: "24/7", label: "Operations support" },
            { value: "03", label: "Connected markets" },
            { value: "01", label: "Single contact point" },
        ],
        newsEyebrow: "Industry knowledge",
        newsTitle: "Policy and market updates",
        readMore: "Read article",
        faqEyebrow: "Useful information",
        faqTitle: "Questions before sending your file",
        faqs: [
            {
                question: "What should I send for a document review?",
                answer: "Send the invoice, packing list, contract, cargo description and planned route. Our team will identify any missing documents.",
            },
            {
                question: "Can VILA SANMYSHI advise on HS codes?",
                answer: "Yes. We review the cargo information, relevant policy and suitable HS code before the declaration is filed.",
            },
            {
                question: "Can customs and cross-border transport be combined?",
                answer: "Yes. The plan is prepared around the cargo, pickup and delivery points, vehicle needs and shipment timeline.",
            },
            {
                question: "How is shipment progress reported?",
                answer: "A single contact tracks the documents, vehicle, border status and final delivery for each shipment.",
            },
        ],
        ctaTitle: "Need your documents checked before filing?",
        ctaBody: "Send your shipment details and our team will return a practical, easy-to-understand plan.",
        ctaButton: "Contact our team",
    },
    th: {
        heroEyebrow: "บริการโลจิสติกส์และศุลกากรที่ลาวบาว",
        heroLead: "การขนส่งข้ามพรมแดน",
        heroHighlight: "และพิธีการศุลกากร",
        heroTail: "ที่ง่ายขึ้น",
        heroBody: "ทีมเดียวดูแลเอกสาร พิธีการ และการขนส่งระหว่างเวียดนาม ลาว และไทย พร้อมอัปเดตที่ชัดเจนทุกขั้นตอน",
        heroImageAlt: "รถบรรทุกสินค้าผ่านพิธีการที่ด่านลาวบาว",
        corridorDesk: "ศูนย์ประสานงาน EWEC",
        corridorStatus: "เชื่อมต่อเส้นทาง",
        corridorPoints: ["กวางตรี", "สะหวันนะเขต", "มุกดาหาร"],
        heroMetrics: [
            { value: "01", label: "ผู้ประสานงานรับผิดชอบ" },
            { value: "06", label: "กลุ่มเอกสารที่ตรวจสอบ" },
            { value: "04", label: "ขั้นตอนควบคุมการขนส่ง" },
            { value: "24/7", label: "สนับสนุนการดำเนินงาน" },
        ],
        trackingEyebrow: "พอร์ทัลติดตามใหม่",
        trackingTitle: "ลูกค้าดูความคืบหน้าได้ และระบบแจ้งเมื่อผ่านพิธีการ",
        trackingBody: "ไทม์ไลน์ สถานะศุลกากร และเอกสารเชื่อมต่อด้วยรหัสติดตามเดียว",
        trackingCta: "เปิดพอร์ทัลติดตาม",
        trackingDemo: "ดูรหัสทดลอง",
        trackingPillars: ["รีเฟรชทุก 5 วินาที", "แจ้งเตือน Zalo และอีเมล", "ไม่เปิดเผยข้อมูลติดต่อ"],
        trackingMock: {
            control: "หน้าควบคุมสำหรับลูกค้า",
            live: "ข้อมูลสด",
            status: "ผ่านพิธีการแล้ว",
            code: "VILA-EWEC-002",
            cargo: "ชิ้นส่วนอิเล็กทรอนิกส์ · 18.4 ตัน",
            route: "ดานัง → ลาวบาว → สะหวันนะเขต",
            progress: "06 / 08 ขั้นตอน",
            metrics: [
                { label: "น้ำหนักรวม", value: "18.4 ตัน" },
                { label: "ถึงสะหวันนะเขต", value: "16:45 วันนี้" },
                { label: "เอกสาร", value: "ครบ 06 / 06" },
                { label: "ผู้ประสานงาน", value: "Nguyen Minh Anh" },
            ],
            notificationTitle: "ผ่านพิธีการเวลา 10:42",
            notificationBody: "ส่งแจ้งเตือน Zalo และอีเมลถึงลูกค้าแล้ว",
            timeline: ["รับเอกสาร", "ยื่นใบขน", "ตรวจสินค้า", "ผ่านพิธีการ", "กำลังขนส่ง"],
        },
        primaryCta: "รับคำปรึกษาฟรี",
        secondaryCta: "ดูบริการ",
        trust: ["ตัวแทนศุลกากรที่ได้รับอนุญาต", "สนับสนุน 24/7", "เส้นทางเวียดนาม – ลาว – ไทย"],
        quickServices: [
            { title: "พิธีการศุลกากร", description: "ตรวจเอกสาร รหัส HS และยื่นใบขนอย่างถูกต้อง" },
            { title: "ขนส่งข้ามพรมแดน", description: "ประสานเส้นทางเวียดนาม – ลาว – ไทยตลอดสาย" },
            { title: "คลังสินค้าและรวมสินค้า", description: "จัดเก็บ รวมเที่ยว และส่งมอบอย่างยืดหยุ่น" },
            { title: "บริการที่ด่านชายแดน", description: "ติดตามรถ เอกสาร และความคืบหน้าพิธีการ" },
        ],
        documentsEyebrow: "ชุดเอกสารที่ใช้บ่อย",
        documentsTitle: "เตรียมเอกสารให้ถูกต้องตั้งแต่ต้น",
        documentsBody: "เอกสารจริงขึ้นอยู่กับประเภทสินค้าและรูปแบบศุลกากร ทีมงานจะตรวจสอบก่อนยื่นใบขน",
        documents: [
            { title: "ใบกำกับสินค้า", meta: "Commercial Invoice" },
            { title: "รายการบรรจุสินค้า", meta: "Packing List" },
            { title: "สัญญาซื้อขาย", meta: "Sales Contract" },
            { title: "เอกสารการขนส่ง", meta: "Bill of Lading / CMR" },
            { title: "หนังสือรับรองถิ่นกำเนิด", meta: "เมื่อจำเป็น" },
            { title: "ใบอนุญาตเฉพาะทาง", meta: "ตามนโยบายสินค้า" },
        ],
        routesEyebrow: "ขอบเขตการเชื่อมต่อ",
        routesTitle: "ผู้ประสานงานเดียวระหว่างเวียดนาม ลาว และไทย",
        routesBody: "เส้นทางจะวางตามประเภทสินค้า จุดรับส่ง และกรอบเวลาของแต่ละเที่ยว",
        routes: [
            { title: "ลาวบาว ↔ แดนสะหวัน", description: "ประสานเอกสารและการส่งมอบที่ด่าน" },
            { title: "กวางตรี ↔ สะหวันนะเขต", description: "วางแผนขนส่งและติดตามการส่งมอบ" },
            { title: "เวียดนาม ↔ ลาว ↔ ไทย", description: "เสนอทางเลือกข้ามพรมแดนสำหรับแต่ละเที่ยว" },
        ],
        servicesEyebrow: "บริการหลัก",
        servicesTitle: "ดูแลครบทุกขั้นตอนของการขนส่ง",
        servicesBody: "ตั้งแต่ตรวจเอกสารจนถึงส่งมอบ ทุกขั้นตอนมีผู้รับผิดชอบและกรอบเวลาชัดเจน",
        allServices: "ดูบริการทั้งหมด",
        fallbackServices: [
            { category: "ศุลกากร", title: "ให้คำปรึกษาเอกสารและรหัส HS", description: "ตรวจนโยบายสินค้า ภาษี และเอกสารก่อนยื่นใบขน" },
            { category: "ขนส่ง", title: "ขนส่งเวียดนาม – ลาว – ไทย", description: "ประสานรถและกำหนดการตลอดเส้นทางระเบียงเศรษฐกิจตะวันออก–ตะวันตก" },
            { category: "คลังสินค้า", title: "จัดเก็บ รวบรวม และส่งมอบ", description: "แผนคลังสินค้าและรวมเที่ยวที่ยืดหยุ่น ช่วยลดเวลาและต้นทุน" },
            { category: "บริการหน้าด่าน", title: "ส่งมอบลาวบาว – แดนสะหวัน", description: "ประสานรถ เอกสาร และการส่งมอบสินค้าที่คู่ด่านสำคัญ" },
            { category: "การปฏิบัติตาม", title: "ตรวจนโยบายสินค้า", description: "ตรวจใบอนุญาต ถิ่นกำเนิด ภาษี และข้อกำหนดเฉพาะก่อนขนส่ง" },
            { category: "การประสานงาน", title: "ติดตามเอกสารและยานพาหนะ", description: "ผู้ประสานงานหลักอัปเดตเอกสาร รถ และความคืบหน้าการส่งมอบตลอดงาน" },
        ],
        processEyebrow: "ขั้นตอนโปร่งใส",
        processTitle: "คุณทราบขั้นตอนถัดไปเสมอ",
        processBody: "VILA SANMYSHI ประสานเอกสารและยานพาหนะในขั้นตอนการทำงานเดียวกัน",
        processSteps: [
            { title: "รับข้อมูล", description: "ตรวจใบแจ้งหนี้ รายการบรรจุ สัญญา และความต้องการส่งมอบ" },
            { title: "ตรวจเอกสาร", description: "ตรวจรหัส HS ใบอนุญาต ภาษี และนโยบายเฉพาะ" },
            { title: "ยื่นและประสานงาน", description: "ยื่นใบขน จัดรถ และรายงานความคืบหน้าที่ด่าน" },
            { title: "ส่งมอบและตรวจสอบ", description: "ส่งสินค้าและสรุปเอกสารกับค่าใช้จ่าย" },
        ],
        proofEyebrow: "เหตุผลที่ลูกค้าเลือกเรา",
        proofTitle: "ประสบการณ์จริงและขั้นตอนที่ชัดเจน",
        proofBody: "ความมั่นใจมาจากทีมที่รู้เส้นทาง เข้าใจพิธีการ และตอบสนองตรงเวลา",
        stats: [
            { value: "2018", label: "ปีที่ก่อตั้ง" },
            { value: "24/7", label: "สนับสนุนการดำเนินงาน" },
            { value: "03", label: "ตลาดที่เชื่อมต่อ" },
            { value: "01", label: "ผู้ประสานงานหลัก" },
        ],
        newsEyebrow: "ความรู้เฉพาะทาง",
        newsTitle: "ข่าวนโยบายและตลาด",
        readMore: "อ่านบทความ",
        faqEyebrow: "ข้อมูลที่ควรรู้",
        faqTitle: "คำถามก่อนส่งเอกสาร",
        faqs: [
            {
                question: "ต้องส่งอะไรบ้างเพื่อตรวจเอกสาร",
                answer: "ส่งใบกำกับสินค้า รายการบรรจุ สัญญา รายละเอียดสินค้า และเส้นทางที่คาดไว้ ทีมงานจะแจ้งเอกสารที่ต้องเพิ่ม",
            },
            {
                question: "VILA SANMYSHI ให้คำปรึกษารหัส HS หรือไม่",
                answer: "ให้บริการ ทีมงานจะตรวจข้อมูลสินค้า นโยบายที่เกี่ยวข้อง และรหัส HS ที่เหมาะสมก่อนยื่นใบขน",
            },
            {
                question: "รวมพิธีการกับขนส่งข้ามพรมแดนได้หรือไม่",
                answer: "ได้ แผนงานจะจัดตามสินค้า จุดรับส่ง ประเภทรถ และกรอบเวลาของแต่ละเที่ยว",
            },
            {
                question: "ติดตามความคืบหน้าของสินค้าอย่างไร",
                answer: "แต่ละเที่ยวมีผู้ประสานงานหลักติดตามเอกสาร รถ สถานะที่ด่าน และการส่งมอบ",
            },
        ],
        ctaTitle: "ต้องการตรวจเอกสารก่อนยื่นใบขนหรือไม่",
        ctaBody: "ส่งรายละเอียดสินค้า แล้วทีมงานจะเสนอแผนที่เหมาะสมและเข้าใจง่าย",
        ctaButton: "ติดต่อทีมงาน",
    },
} as const;
export const fallbackImages = [
    "/images/services/customs.png",
    "/images/services/cross-border-premium.png",
    "/images/editorial/warehouse.jpg",
    "/images/services/hub.png",
    "/images/services/fulfillment-premium.png",
    "/images/editorial/container-port.jpg",
];
