export const editorialCopy = {
  vi: {
    eyebrow: "VỮNG NIỀM TIN · VƯƠN KẾT NỐI",
    headline: "Kết nối giao thương.",
    headlineMiddle: "Đồng hành",
    headlineAccent: "vươn xa.",
    intro: "Từ một lô hàng đến những hành trình lớn. VILA SANMYSHI đồng hành cùng doanh nghiệp trong từng thủ tục hải quan, từng chuyến hàng xuyên biên giới.",
    explore: "Khám phá dịch vụ",
    about: "Câu chuyện của chúng tôi",
    assurance: "Tận tâm từng chặng đường",
    assuranceDetail: "Một đầu mối. Trọn sự an tâm.",
    imageCaption: "Kết nối Việt Nam · Lào · Thái Lan",
    imageAlt: "Xe vận tải trên cầu, kết nối những hành trình giao thương",
    gateAlt: "Cửa khẩu Quốc tế Lao Bảo, Quảng Trị",
    since: "Đồng hành từ 2018",
    scroll: "Khám phá VILA",
    trackingTitle: "Lô hàng của bạn đang ở đâu?",
    trackingHint: "Theo dõi hành trình, an tâm kế hoạch.",
    trackingPlaceholder: "Nhập mã vận đơn của bạn",
    trackingButton: "Tra cứu",
    trackingLabel: "Mã tra cứu lô hàng",
    storyEyebrow: "KHÔNG CHỈ LÀ VẬN CHUYỂN",
    storyTitle: "Chúng tôi chuyên chở",
    storyAccent: "cả niềm tin.",
    storyBody: "Am hiểu địa phương, kết nối khu vực. Từ Lao Bảo, chúng tôi giúp hành trình giao thương của bạn trở nên thuận lợi hơn bằng sự tận tâm và một quy trình minh bạch.",
    servicesTitle: "Mỗi nhu cầu.",
    servicesAccent: "Một giải pháp phù hợp.",
    servicesBody: "Kết nối con người, phương tiện và chuyên môn để mỗi lô hàng được chăm sóc trọn vẹn.",
    detail: "Tìm hiểu dịch vụ",
    networkTitle: "Gần hơn mọi",
    networkAccent: "khoảng cách.",
    networkBody: "Trên hành lang kinh tế Đông – Tây, chúng tôi kết nối Việt Nam, Lào và Thái Lan bằng sự thấu hiểu từng tuyến đường, từng cửa khẩu.",
    networkCta: "Khám phá mạng lưới",
    networkTag: "HÀNH LANG KINH TẾ ĐÔNG – TÂY",
    countries: ["Việt Nam", "Lào", "Thái Lan"],
    processTitle: "Rõ từng bước.",
    processAccent: "Vững từng hành trình.",
    newsTitle: "Góc nhìn &",
    newsAccent: "chuyển động.",
    allNews: "Tất cả bài viết",
    documents: "Xem danh mục chứng từ cần chuẩn bị",
    ctaEyebrow: "HÀNH TRÌNH MỚI BẮT ĐẦU TỪ MỘT KẾT NỐI",
    ctaTitle: "Cùng bạn mở lối",
    ctaAccent: "giao thương.",
    ctaBody: "Chia sẻ nhu cầu của bạn. Chúng tôi sẽ cùng tìm ra giải pháp phù hợp.",
  },
  en: {
    eyebrow: "BUILT ON TRUST · CONNECTED FOR GROWTH",
    headline: "Connecting trade.",
    headlineMiddle: "Moving",
    headlineAccent: "forward together.",
    intro: "From a single shipment to bigger ambitions. VILA SANMYSHI supports your business through every customs procedure and every cross-border journey.",
    explore: "Explore our services",
    about: "Discover our story",
    assurance: "Care at every milestone",
    assuranceDetail: "One partner. Complete peace of mind.",
    imageCaption: "Connecting Vietnam · Laos · Thailand",
    imageAlt: "A freight truck crossing a bridge, connecting trade routes",
    gateAlt: "Lao Bao International Border Gate, Quang Tri",
    since: "By your side since 2018",
    scroll: "Discover VILA",
    trackingTitle: "Where is your shipment?",
    trackingHint: "Follow its journey. Plan with confidence.",
    trackingPlaceholder: "Enter your tracking code",
    trackingButton: "Track",
    trackingLabel: "Shipment tracking code",
    storyEyebrow: "MORE THAN MOVING CARGO",
    storyTitle: "We carry your cargo.",
    storyAccent: "And your trust.",
    storyBody: "Local knowledge. Regional connections. From Lao Bao, we make your trade journey simpler with dedicated people and a transparent process.",
    servicesTitle: "Every need.",
    servicesAccent: "The right solution.",
    servicesBody: "Bringing people, transport and expertise together to care for your shipment from start to finish.",
    detail: "Explore service",
    networkTitle: "Bringing every",
    networkAccent: "destination closer.",
    networkBody: "Across the East–West Economic Corridor, we connect Vietnam, Laos and Thailand with a deep understanding of every route and border crossing.",
    networkCta: "Explore our network",
    networkTag: "EAST–WEST ECONOMIC CORRIDOR",
    countries: ["Vietnam", "Laos", "Thailand"],
    processTitle: "Clear at every step.",
    processAccent: "Confident all the way.",
    newsTitle: "Insights &",
    newsAccent: "perspectives.",
    allNews: "All articles",
    documents: "View the document checklist",
    ctaEyebrow: "EVERY NEW JOURNEY STARTS WITH A CONNECTION",
    ctaTitle: "Opening new routes",
    ctaAccent: "together.",
    ctaBody: "Tell us what you need. Let’s find the right solution for your business.",
  },
  th: {
    eyebrow: "สร้างความไว้วางใจ · เชื่อมต่อการเติบโต",
    headline: "เชื่อมต่อการค้า",
    headlineMiddle: "เคียงข้างคุณ",
    headlineAccent: "ไปได้ไกลกว่า",
    intro: "จากสินค้าหนึ่งเที่ยวสู่เป้าหมายที่ยิ่งใหญ่ VILA SANMYSHI เคียงข้างธุรกิจของคุณในทุกขั้นตอนศุลกากรและทุกเส้นทางข้ามพรมแดน",
    explore: "สำรวจบริการของเรา",
    about: "เรื่องราวของเรา",
    assurance: "ใส่ใจทุกเส้นทาง",
    assuranceDetail: "ผู้ประสานงานเดียว วางใจได้ตลอดทาง",
    imageCaption: "เชื่อมต่อเวียดนาม · ลาว · ไทย",
    imageAlt: "รถบรรทุกข้ามสะพานเชื่อมต่อเส้นทางการค้า",
    gateAlt: "ด่านพรมแดนนานาชาติลาวบาว กว๋างจิ",
    since: "เคียงข้างคุณตั้งแต่ 2018",
    scroll: "รู้จัก VILA",
    trackingTitle: "สินค้าของคุณอยู่ที่ไหน?",
    trackingHint: "ติดตามการเดินทาง วางแผนอย่างมั่นใจ",
    trackingPlaceholder: "กรอกรหัสติดตามสินค้า",
    trackingButton: "ติดตาม",
    trackingLabel: "รหัสติดตามสินค้า",
    storyEyebrow: "มากกว่าการขนส่ง",
    storyTitle: "เราขนส่งสินค้า",
    storyAccent: "พร้อมความไว้วางใจ",
    storyBody: "รู้ลึกในท้องถิ่น เชื่อมต่อทั้งภูมิภาค จากลาวบาว เราช่วยให้การค้าของคุณราบรื่นด้วยความใส่ใจและกระบวนการที่โปร่งใส",
    servicesTitle: "ทุกความต้องการ",
    servicesAccent: "มีทางออกที่เหมาะสม",
    servicesBody: "เชื่อมบุคลากร ยานพาหนะ และความเชี่ยวชาญ เพื่อดูแลสินค้าของคุณตั้งแต่ต้นจนจบ",
    detail: "ดูรายละเอียดบริการ",
    networkTitle: "เชื่อมทุกจุดหมาย",
    networkAccent: "ให้ใกล้ยิ่งขึ้น",
    networkBody: "บนระเบียงเศรษฐกิจตะวันออก–ตะวันตก เราเชื่อมเวียดนาม ลาว และไทย ด้วยความเข้าใจในทุกเส้นทางและด่านพรมแดน",
    networkCta: "สำรวจเครือข่ายของเรา",
    networkTag: "ระเบียงเศรษฐกิจตะวันออก–ตะวันตก",
    countries: ["เวียดนาม", "ลาว", "ไทย"],
    processTitle: "ชัดเจนทุกขั้นตอน",
    processAccent: "มั่นใจทุกเส้นทาง",
    newsTitle: "มุมมองและ",
    newsAccent: "ความเคลื่อนไหว",
    allNews: "บทความทั้งหมด",
    documents: "ดูรายการเอกสารที่ต้องเตรียม",
    ctaEyebrow: "ทุกการเดินทางใหม่เริ่มจากการเชื่อมต่อ",
    ctaTitle: "เปิดเส้นทางการค้า",
    ctaAccent: "ไปด้วยกัน",
    ctaBody: "บอกความต้องการของคุณ เราจะร่วมกันค้นหาทางออกที่เหมาะสม",
  },
};
